import Head from "next/head";
import { Container } from "@nextui-org/react";
import { useEffect, useState, useCallback, useMemo } from "react";
import axios from "axios";

function Home() {
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const fetchUser = async () => {
      setLoading(true);
      const { data } = await axios.get("/api/auth/current-user");
      setLoading(false);
      setUser(data);
    };
    fetchUser();
  }, []);

  return (
    <div>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        display="flex"
        alignItems="center"
        justify="center"
        css={{ h: "100vh" }}
      >
        <h1>
          {loading ? "Loading...." : user ? "Authenticated" : "Landing Page"}
        </h1>
      </Container>
    </div>
  );
}

export default Home;
